all:
	arm-linux-gcc -o ex06_IPV6_Alarm ex06_IPV6_Alarm.c -Iinclude -Llib -llibsmscb -lipv6comm -lpthread -L/usr/local/Trolltech/QtEmbedded-4.7.0-arm/lib -lQtCore -lQtNetwork

clean:
	rm -f ex06_IPV6_Alarm
