######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 13 10:18:16 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyWid.h
SOURCES += main.cpp MyWid.cpp
